[[pages]]
path = "home.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "blind_test.py"
name = "Blind Test"
icon = ":test_tube:"

[[pages]]
path = "advice_app.py"
name = "Carousel"
icon = ":vibration_mode:"

[[pages]]
path = "lora_explainer.py"
name = "Beyond BaseModel"
icon = ":memo:"

[[pages]]
path = "conclusion.py"
name = "Conclusion"
icon = "🎯"

[[pages]]
path = "prompt.py"
name = "Prompt"
icon = ":camera:"

[[pages]]
path = "appendix.py"
name = "Appendix"
icon = "📎"

[[pages]]
path = "contacts.py"
name = "Contact us"
icon = ":envelope_with_arrow:"